### ISSUE TITLE
How to use this project for creating iOS device payload?

### ISSUE THREAD

**Issue by uGiFarukh** [entynetproject/mouse#4]
Hello,

I have been trying to use this project on my Ubuntu 20.04 server to create a payload for an iOS device and then deploy the payload on my phone and test the features. How can I do this? The available guides are not extensive enough. I am a beginner. Is it possible for you to guide me how to achieve this?

Thank You.

**Comment by game-lover** [comment]
Why not?

**Comment by uGiFarukh** [comment]
How to do it?

**Comment by game-lover** [comment]
This is not tool for creating iOS payloads. This tool contains them. You learn Objective-C for creating iOS payloads and see some payloads in [Metasploit Framework](https://github.com/rapid7/metasploit-framework). Also you can read files in substrate directory

**Comment by uGiFarukh** [comment]
If this tool contains iOS payloads then how can I deploy and use them? I cannot seem to find a way or guide to show me how to use them in my iOS device?

**Comment by game-lover** [comment]
You need macOS with Xcode to build payload

**Comment by game-lover** [comment]
Guide - [README.md](https://github.com/neoneggplant/EggShell#About)

**Comment by uGiFarukh** [comment]
After that how can I deploy it to the target iOS device?

**Comment by enty8080** [comment]
iOS device must be jailbroken :( And payload does not supports iOS 13, sorry.
